# Generated by Django 5.2 on 2026-05-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF Fayl'), ('url', 'URL Havola'), ('text', 'Matn')], max_length=10, verbose_name='Tur')),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/pdfs/', verbose_name='PDF Fayl')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL Havola')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Matn')),
                ('raw_text', models.TextField(blank=True, verbose_name='Ajratilgan matn')),
                ('is_evaluated', models.BooleanField(default=False, verbose_name='Baholandi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='subjects.topic', verbose_name='Mavzu')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Yuklagan foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Resurs',
                'verbose_name_plural': 'Resurslar',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RelevanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Ball (0.0 - 1.0)')),
                ('label', models.CharField(choices=[('high', 'Yuqori'), ('medium', "O'rta"), ('low', 'Past')], max_length=10, verbose_name='Daraja')),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('key_matches', models.JSONField(default=list, verbose_name="Mos kalit so'zlar")),
                ('missing_topics', models.JSONField(default=list, verbose_name='Yetishmayotgan mavzular')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='subjects.topic', verbose_name='Mavzu')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='resources.resource', verbose_name='Resurs')),
            ],
            options={
                'verbose_name': 'Dolzarblik bali',
                'verbose_name_plural': 'Dolzarblik ballari',
                'ordering': ['-score'],
            },
        ),
    ]
